{
  "title": "audit_logs",
  "services": {
    "query": {
      "idQueue": [
        1,
        2,
        3,
        4
      ],
      "list": {
        "0": {
          "query": "*:*",
          "alias": "",
          "color": "#7EB26D",
          "id": 0,
          "pin": false,
          "type": "lucene"
        }
      },
      "ids": [
        0
      ]
    },
    "filter": {
      "idQueue": [
        2
      ],
      "list": {
        "0": {
          "from": "NOW/DAY-30DAY",
          "to": "NOW/DAY%2B1DAY",
          "field": "timestamp_tdt",
          "type": "time",
          "fromDateObj": "2017-07-01T13:42:42.591Z",
          "toDateObj": "2017-07-31T13:42:42.591Z",
          "mandate": "must",
          "active": true,
          "alias": "",
          "id": 0
        },
        "1": {
          "type": "terms",
          "field": "request.method_s",
          "value": "GET",
          "mandate": "mustNot",
          "active": true,
          "alias": "",
          "id": 1
        }
      },
      "ids": [
        1,
        0
      ]
    }
  },
  "rows": [
    {
      "title": "Query and Time Window",
      "height": "50px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "error": "",
          "span": 6,
          "editable": true,
          "type": "timepicker",
          "loadingEditor": false,
          "status": "Stable",
          "mode": "relative",
          "time_options": [
            "5m",
            "15m",
            "1h",
            "6h",
            "12h",
            "24h",
            "7d",
            "30d",
            "90d",
            "1y",
            "5y"
          ],
          "timespan": "30d",
          "timefield": "timestamp_tdt",
          "timeformat": "",
          "refresh": {
            "enable": false,
            "interval": 30,
            "min": 3
          },
          "filter_id": 0,
          "spyable": true,
          "title": "Time Window"
        },
        {
          "error": false,
          "span": 4,
          "editable": true,
          "group": [
            "default"
          ],
          "type": "query",
          "label": "Search",
          "history": [],
          "remember": 10,
          "pinned": true,
          "query": "*:*",
          "title": "Search",
          "spyable": true,
          "def_type": ""
        },
        {
          "span": 2,
          "editable": true,
          "type": "hits",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&fq=request.header.fusion-user-name_ss:*&fq=timestamp_tdt:[NOW/DAY-30DAY%20TO%20NOW/DAY%2B1DAY]&fq=-request.method_s:\"GET\"&stats=true&stats.field=id&wt=json&rows=0\n",
            "basic_query": "",
            "custom": ""
          },
          "style": {
            "font-size": "14pt"
          },
          "arrangement": "horizontal",
          "chart": "total",
          "counter_pos": "above",
          "donut": false,
          "tilt": false,
          "labels": true,
          "spyable": true,
          "title": "Total Hits",
          "show_queries": true,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "metrics": [
            {
              "type": "count",
              "field": "id",
              "decimalDigits": 0,
              "label": "",
              "value": "15003"
            }
          ]
        }
      ]
    },
    {
      "title": "Filters",
      "height": "200px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 6,
          "editable": true,
          "type": "histogram",
          "loadingEditor": false,
          "mode": "count",
          "time_field": "timestamp_tdt",
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&fq=request.header.fusion-user-name_ss:*&wt=json&rows=0&fq=timestamp_tdt:[NOW/DAY-30DAY%20TO%20NOW/DAY%2B1DAY]&fq=-request.method_s:\"GET\"&facet=true&facet.range=timestamp_tdt&facet.range.start=NOW/DAY-30DAY&facet.range.end=NOW/DAY%2B1DAY&facet.range.gap=%2B12HOUR\n",
            "custom": ""
          },
          "max_rows": 100000,
          "value_field": null,
          "group_field": null,
          "auto_int": true,
          "resolution": 100,
          "interval": "12h",
          "intervals": [
            "auto",
            "1s",
            "1m",
            "5m",
            "10m",
            "30m",
            "1h",
            "3h",
            "12h",
            "1d",
            "1w",
            "1M",
            "1y"
          ],
          "fill": 0,
          "linewidth": 3,
          "timezone": "browser",
          "spyable": true,
          "zoomlinks": true,
          "bars": true,
          "stack": true,
          "points": false,
          "lines": false,
          "legend": true,
          "x-axis": true,
          "y-axis": true,
          "percentage": false,
          "interactive": true,
          "options": true,
          "tooltip": {
            "value_type": "cumulative",
            "query_as_alias": false
          },
          "title": "Event Counts",
          "lines_smooth": false,
          "show_queries": true,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "sum_value": false
        },
        {
          "error": false,
          "span": 6,
          "editable": true,
          "spyable": true,
          "group": [
            "default"
          ],
          "type": "filtering"
        }
      ]
    },
    {
      "title": "Graph",
      "height": "250px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 3,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&fq=request.header.fusion-user-name_ss:*&wt=json&fq=timestamp_tdt:[NOW/DAY-30DAY%20TO%20NOW/DAY%2B1DAY]&fq=-request.method_s:\"GET\"&facet=true&facet.field=request.method_s&facet.limit=30&facet.missing=true&f.request.method_s.facet.sort=count",
            "custom": ""
          },
          "mode": "count",
          "field": "request.method_s",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 30,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "logAxis": false,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "lastColor": "rgb(100,142,87)",
          "spyable": true,
          "show_queries": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "Method",
          "sortBy": "count",
          "exportSize": 10000
        },
        {
          "span": 3,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&fq=request.header.fusion-user-name_ss:*&wt=json&fq=timestamp_tdt:[NOW/DAY-30DAY%20TO%20NOW/DAY%2B1DAY]&fq=-request.method_s:\"GET\"&facet=true&facet.field=request.header.fusion-user-name_ss&facet.limit=30&facet.missing=true&f.request.header.fusion-user-name_ss.facet.sort=count",
            "custom": ""
          },
          "mode": "count",
          "field": "request.header.fusion-user-name_ss",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 30,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "logAxis": false,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "lastColor": "",
          "spyable": true,
          "show_queries": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "User",
          "sortBy": "count",
          "exportSize": 10000
        },
        {
          "span": 6,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&fq=request.header.fusion-user-name_ss:*&wt=json&fq=timestamp_tdt:[NOW/DAY-30DAY%20TO%20NOW/DAY%2B1DAY]&fq=-request.method_s:\"GET\"&facet=true&facet.field=request.path_s&facet.limit=30&facet.missing=true&f.request.path_s.facet.sort=count",
            "custom": ""
          },
          "mode": "count",
          "field": "request.path_s",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 30,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "logAxis": false,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "lastColor": "",
          "spyable": true,
          "show_queries": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "Request Path",
          "sortBy": "count",
          "exportSize": 10000
        }
      ]
    },
    {
      "title": "Table",
      "height": "150px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 12,
          "editable": true,
          "type": "table",
          "loadingEditor": false,
          "status": "Stable",
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&fq=request.header.fusion-user-name_ss:*&fq=timestamp_tdt:[NOW/DAY-30DAY%20TO%20NOW/DAY%2B1DAY]&fq=-request.method_s:\"GET\"&sort=timestamp_tdt desc&wt=json&rows=200",
            "basic_query": "q=*%3A*&fq=request.header.fusion-user-name_ss:*&fq=timestamp_tdt:[NOW/DAY-30DAY%20TO%20NOW/DAY%2B1DAY]&fq=-request.method_s:\"GET\"&sort=timestamp_tdt desc",
            "custom": ""
          },
          "size": 100,
          "pages": 2,
          "offset": 0,
          "sort": [
            "timestamp_tdt",
            "desc"
          ],
          "group": "default",
          "style": {
            "font-size": "9pt"
          },
          "overflow": "min-height",
          "fields": [
            "timestamp_tdt",
            "request.header.fusion-user-name_ss",
            "request.method_s",
            "request.path_s",
            "response.status_i",
            "time_l"
          ],
          "highlight": [],
          "sortable": true,
          "header": true,
          "paging": true,
          "field_list": false,
          "trimFactor": 300,
          "normTimes": true,
          "spyable": true,
          "saveOption": "json",
          "exportSize": 200,
          "exportAll": true,
          "displayLinkIcon": true,
          "imageFields": [],
          "imgFieldWidth": "auto",
          "imgFieldHeight": "85px",
          "title": "Table panel",
          "important_fields": [
            "_version_",
            "host_s",
            "id",
            "port_s",
            "request.header.accept-encoding_ss",
            "request.header.accept_ss",
            "request.header.content-length_ss",
            "request.header.content-type_ss",
            "request.header.fusion-auth-permissions_ss",
            "request.header.fusion-auth-version_ss",
            "request.header.fusion-session-id_ss",
            "request.header.fusion-user-auth-realm_ss",
            "request.header.fusion-user-id_ss",
            "request.header.fusion-user-name_ss",
            "request.header.host_ss",
            "request.header.user-agent_ss",
            "request.header.via_ss",
            "request.media.type_s",
            "request.method_s",
            "request.path_s",
            "request.uri_s",
            "response.header.content-type_ss",
            "response.header.server_ss",
            "response.header.transfer-encoding_ss",
            "response.media.type_s",
            "response.status_i",
            "time_l",
            "timestamp_tdt"
          ],
          "show_queries": true,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "maxNumCalcTopFields": 20,
          "calcTopFieldValuesFromAllData": false
        }
      ]
    }
  ],
  "editable": true,
  "index": {
    "interval": "none",
    "pattern": "[logstash-]YYYY.MM.DD",
    "default": "_all"
  },
  "style": "light",
  "failover": false,
  "panel_hints": true,
  "loader": {
    "save_gist": false,
    "save_elasticsearch": true,
    "save_local": true,
    "save_default": true,
    "save_temp": true,
    "save_temp_ttl_enable": true,
    "save_temp_ttl": "30d",
    "load_gist": true,
    "load_elasticsearch": true,
    "load_elasticsearch_size": 20,
    "load_local": true,
    "hide": false,
    "dropdown_collections": false,
    "save_as_public": false
  },
  "solr": {
    "server": "/api/apollo/solr/",
    "core_name": "audit_logs",
    "core_list": [
      "BestBuy_rules",
      "UserPrefs_signals",
      "KM_signals_aggr",
      "default_signals",
      "EnterpriseSearch2_signals_aggr",
      "UserPrefs_signals_aggr",
      "system_metrics",
      "system_blobs",
      "EnterpriseSearch_signals",
      "POI_signals",
      "default_syn_c3lub255bXMudHh0",
      "logs",
      "EnterpriseSearch",
      "citibikerides_signals",
      "EnterpriseSearch_signals_aggr",
      "citibikerides_logs",
      "POI_signals_aggr",
      "KM_logs",
      "POI",
      "default_signals_aggr",
      "EnterpriseSearch2_signals",
      "Doctors",
      "BestBuy_signals_aggr",
      "EnterpriseSearch2_logs",
      "BestBuy_signals",
      "BestBuy_syn_c3lub255bXMudHh0",
      "UserPrefs_logs",
      "EnterpriseSearch_syn_c3lub255bXMudHh0",
      "EnterpriseSearch2",
      "system_messages",
      "recommender_models",
      "citibikerides_signals_aggr",
      "audit_logs",
      "Doctors_signals_aggr",
      "POI_logs",
      "KM_signals",
      "default",
      "default_logs",
      "BestBuy_logs",
      "system_jobs_history",
      "BestBuy",
      "citibikerides",
      "UserPrefs",
      "Doctors_signals",
      "KM",
      "EnterpriseSearch_stored_parameters",
      "Doctors_logs",
      "system_history",
      "BestBuy_stored_parameters",
      "EnterpriseSearch_logs"
    ],
    "global_params": "&fq=request.header.fusion-user-name_ss:*"
  },
  "username": "admin"
}