{
  "title": "Search Analytics V3",
  "services": {
    "query": {
      "idQueue": [
        1,
        2,
        3,
        4
      ],
      "list": {
        "0": {
          "query": "*:*",
          "alias": "",
          "color": "#7EB26D",
          "id": 0,
          "pin": false,
          "type": "lucene"
        }
      },
      "ids": [
        0
      ]
    },
    "filter": {
      "idQueue": [
        1,
        2
      ],
      "list": {
        "0": {
          "from": "NOW/YEAR-1YEAR",
          "to": "NOW/YEAR%2B1YEAR",
          "field": "timestamp_tdt",
          "type": "time",
          "fromDateObj": "2016-07-31T13:44:27.214Z",
          "toDateObj": "2017-07-31T13:44:27.215Z",
          "mandate": "must",
          "active": true,
          "alias": "",
          "id": 0
        }
      },
      "ids": [
        0
      ]
    }
  },
  "rows": [
    {
      "title": "Query and Time Window",
      "height": "50px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "error": "",
          "span": 6,
          "editable": true,
          "type": "timepicker",
          "loadingEditor": false,
          "status": "Stable",
          "mode": "relative",
          "time_options": [
            "5m",
            "15m",
            "1h",
            "6h",
            "12h",
            "24h",
            "7d",
            "30d",
            "90d",
            "1y",
            "5y"
          ],
          "timespan": "1y",
          "timefield": "timestamp_tdt",
          "timeformat": "",
          "refresh": {
            "enable": false,
            "interval": 30,
            "min": 3
          },
          "filter_id": 0,
          "spyable": true,
          "title": "Time Window"
        },
        {
          "error": false,
          "span": 4,
          "editable": true,
          "group": [
            "default"
          ],
          "type": "query",
          "label": "Search",
          "history": [
            "*:*",
            "strange",
            "search"
          ],
          "remember": 10,
          "pinned": true,
          "query": "*:*",
          "title": "Search",
          "spyable": true,
          "def_type": ""
        },
        {
          "span": 2,
          "editable": true,
          "type": "hits",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&stats=true&stats.field=id&wt=json&rows=0\n",
            "basic_query": "",
            "custom": ""
          },
          "style": {
            "font-size": "14pt"
          },
          "arrangement": "horizontal",
          "chart": "total",
          "counter_pos": "above",
          "donut": false,
          "tilt": false,
          "labels": true,
          "spyable": true,
          "title": "Total Hits",
          "show_queries": true,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "metrics": [
            {
              "type": "count",
              "field": "id",
              "decimalDigits": 0,
              "label": "",
              "value": "539"
            }
          ]
        }
      ]
    },
    {
      "title": "Time Filter",
      "height": "250px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 6,
          "editable": true,
          "type": "histogram",
          "loadingEditor": false,
          "mode": "count",
          "time_field": "timestamp_tdt",
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&rows=0&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&facet=true&facet.range=timestamp_tdt&facet.range.start=NOW/YEAR-1YEAR&facet.range.end=NOW/YEAR%2B1YEAR&facet.range.gap=%2B1DAY\n",
            "custom": ""
          },
          "max_rows": 100000,
          "value_field": null,
          "group_field": null,
          "auto_int": true,
          "resolution": 100,
          "interval": "1d",
          "intervals": [
            "auto",
            "1s",
            "1m",
            "5m",
            "10m",
            "30m",
            "1h",
            "3h",
            "12h",
            "1d",
            "1w",
            "1M",
            "1y"
          ],
          "fill": 0,
          "linewidth": 3,
          "timezone": "browser",
          "spyable": true,
          "zoomlinks": true,
          "bars": true,
          "stack": true,
          "points": false,
          "lines": false,
          "legend": true,
          "x-axis": true,
          "y-axis": true,
          "percentage": false,
          "interactive": true,
          "options": true,
          "tooltip": {
            "value_type": "cumulative",
            "query_as_alias": false
          },
          "title": "Event Counts",
          "lines_smooth": false,
          "show_queries": true,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "sum_value": false
        },
        {
          "span": 6,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&facet=true&facet.field=q_s&facet.limit=10&facet.missing=true&f.q_s.facet.sort=count&fq=numdocs_l:[1 TO *]&fq=-{!term f=q_s}*:*",
            "custom": "&fq=numdocs_l:[1 TO *]&fq=-{!term f=q_s}*:*"
          },
          "mode": "count",
          "field": "q_s",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 10,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "lastColor": "",
          "spyable": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "title": "Top 10 Searches",
          "show_queries": true,
          "logAxis": false,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "sortBy": "count",
          "exportSize": 10000
        }
      ]
    },
    {
      "title": "Bad Searches",
      "height": "240px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 6,
          "editable": true,
          "type": "table",
          "loadingEditor": false,
          "status": "Stable",
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&sort=timestamp_tdt desc&wt=json&rows=100",
            "basic_query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&sort=timestamp_tdt desc",
            "custom": "&fq=-{!term f=req_lw_q_orig_ss}*:*&fq=clicked_count_l:0&fq=numdocs_l:[1 TO *]"
          },
          "size": 20,
          "pages": 5,
          "offset": 0,
          "sort": [
            "timestamp_tdt",
            "desc"
          ],
          "sortable": true,
          "group": "default",
          "style": {
            "font-size": "9pt"
          },
          "overflow": "height",
          "fields": [
            "timestamp_tdt",
            "q_s",
            "numdocs_l",
            "req_lw_user_ss"
          ],
          "important_fields": [
            "_version_",
            "clicked_count_l",
            "collection_s",
            "httpmethod_s",
            "id",
            "numdocs_l",
            "q_s",
            "q_txt",
            "qtime_l",
            "req_boost_ss",
            "req_defType_ss",
            "req_ds_EnterpriseSearch-Sharepoint_ss",
            "req_f.DeptName_s.facet.mincount_ss",
            "req_f.DeptName_s.facet.missing_ss",
            "req_f.DeptName_s.facet.sort_ss",
            "req_f.EmployeeTitle_s.facet.mincount_ss",
            "req_f.EmployeeTitle_s.facet.missing_ss",
            "req_f.EmployeeTitle_s.facet.sort_ss",
            "req_f.authorsX_ss.facet.limit_ss",
            "req_f.authorsX_ss.facet.mincount_ss",
            "req_f.authorsX_ss.facet.missing_ss",
            "req_f.authorsX_ss.facet.sort_ss",
            "req_f.data_sourceX_s.facet.limit_ss",
            "req_f.data_sourceX_s.facet.mincount_ss",
            "req_f.data_sourceX_s.facet.missing_ss",
            "req_f.data_sourceX_s.facet.sort_ss",
            "req_f.extracted_namesX_ss.facet.mincount_ss",
            "req_f.extracted_namesX_ss.facet.missing_ss",
            "req_f.file_formatX_s.facet.mincount_ss",
            "req_f.file_formatX_s.facet.missing_ss",
            "req_f.file_formatX_s.facet.sort_ss",
            "req_f.question_typeX_s.facet.mincount_ss",
            "req_f.question_typeX_s.facet.missing_ss",
            "req_f.topicX_s.facet.mincount_ss",
            "req_f.topicX_s.facet.missing_ss",
            "req_facet.field_ss",
            "req_facet.pivot.min.count_ss",
            "req_facet.pivot_ss",
            "req_facet_ss",
            "req_fl_ss",
            "req_fq_ss",
            "req_hl.fl_ss",
            "req_hl.fragsize_ss",
            "req_hl.preserveMulti_ss",
            "req_hl.q_ss",
            "req_hl_ss",
            "req_isFusionQuery_ss",
            "req_lw.pipelineId_ss",
            "req_lw_appName_ss",
            "req_lw_browser_ss",
            "req_lw_city_ss",
            "req_lw_coord_ss",
            "req_lw_country_ss",
            "req_lw_facet.pivot_ss",
            "req_lw_ip_address_ss",
            "req_lw_language_ss",
            "req_lw_q_orig_ss",
            "req_lw_signals_filter_ss",
            "req_lw_state_ss",
            "req_lw_userAgent_ss",
            "req_lw_user_device_ss",
            "req_lw_user_ss",
            "req_lw_uuid_ss",
            "req_lw_zip_code_ss",
            "req_pf_ss",
            "req_q_ss",
            "req_qf_ss",
            "req_rows_ss",
            "req_start_ss",
            "req_wrapped_ds_EnterpriseSearch-Sharepoint_ss",
            "req_wt_ss",
            "timestamp_tdt",
            "totaltime_l"
          ],
          "highlight": [],
          "header": true,
          "paging": true,
          "field_list": false,
          "trimFactor": 300,
          "normTimes": true,
          "spyable": true,
          "saveOption": "json",
          "exportSize": 100,
          "exportAll": true,
          "displayLinkIcon": true,
          "imageFields": [],
          "imgFieldWidth": "auto",
          "imgFieldHeight": "85px",
          "show_queries": true,
          "maxNumCalcTopFields": 20,
          "calcTopFieldValuesFromAllData": false,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "Abandoned Searches"
        },
        {
          "span": 6,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&facet=true&facet.field=q_s&facet.limit=10&facet.missing=true&f.q_s.facet.sort=count&fq=numdocs_l:0&fq=-{!term f=q_s}*:*",
            "custom": "&fq=numdocs_l:0&fq=-{!term f=q_s}*:*"
          },
          "mode": "count",
          "field": "q_s",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 10,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "lastColor": "",
          "spyable": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "title": "Top 10 Searches with Zero Result",
          "show_queries": true,
          "logAxis": false,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "sortBy": "count",
          "exportSize": 10000
        }
      ]
    },
    {
      "title": "Query Time",
      "height": "240px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 4,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&stats=true&stats.facet=q_s&stats.field=qtime_l&facet.missing=true&f.q_s.facet.sort=count&fq=-{!term f=req_q_s}*:*",
            "custom": "&fq=-{!term f=req_q_s}*:*"
          },
          "mode": "mean",
          "field": "q_s",
          "stats_field": "qtime_l",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 10,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "lastColor": "",
          "spyable": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "title": "Avg Query Time in ms by Search Terms",
          "show_queries": true,
          "logAxis": false,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "sortBy": "count",
          "exportSize": 10000
        },
        {
          "span": 4,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&stats=true&stats.facet=q_s&stats.field=qtime_l&facet.missing=true&f.q_s.facet.sort=count&fq=-{!term f=q_s}*:*",
            "custom": "&fq=-{!term f=q_s}*:*"
          },
          "mode": "min",
          "field": "q_s",
          "stats_field": "qtime_l",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 10,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "lastColor": "rgb(126,178,109)",
          "spyable": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "title": "Min Query Time in ms  by Search Terms",
          "show_queries": true,
          "logAxis": false,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "sortBy": "count",
          "exportSize": 10000
        },
        {
          "span": 4,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&stats=true&stats.facet=q_s&stats.field=qtime_l&facet.missing=true&f.q_s.facet.sort=count&fq=-{!term f=q_s}*:*",
            "custom": "&fq=-{!term f=q_s}*:*"
          },
          "mode": "max",
          "field": "q_s",
          "stats_field": "qtime_l",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 10,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "lastColor": "rgb(126,178,109)",
          "spyable": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "title": "Max Query Time in ms by Search Terms",
          "show_queries": true,
          "logAxis": false,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "sortBy": "count",
          "exportSize": 10000
        }
      ]
    },
    {
      "title": "User Info",
      "height": "240px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 4,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&facet=true&facet.field=req_lw_user_device_ss&facet.limit=20&facet.missing=true&f.req_lw_user_device_ss.facet.sort=count",
            "custom": ""
          },
          "mode": "count",
          "field": "req_lw_user_device_ss",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 20,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "logAxis": false,
          "arrangement": "horizontal",
          "chart": "pie",
          "counter_pos": "above",
          "lastColor": "rgb(126,178,109)",
          "spyable": true,
          "show_queries": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "User Device",
          "sortBy": "count",
          "exportSize": 10000
        },
        {
          "span": 4,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&facet=true&facet.field=req_lw_browser_ss&facet.limit=20&facet.missing=true&f.req_lw_browser_ss.facet.sort=count",
            "custom": ""
          },
          "mode": "count",
          "field": "req_lw_browser_ss",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 20,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "logAxis": false,
          "arrangement": "horizontal",
          "chart": "pie",
          "counter_pos": "above",
          "lastColor": "",
          "spyable": true,
          "show_queries": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "User Browser",
          "sortBy": "count",
          "exportSize": 10000
        },
        {
          "span": 4,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&facet=true&facet.field=req_lw_ip_address_ss&facet.limit=20&facet.missing=true&f.req_lw_ip_address_ss.facet.sort=count",
            "custom": ""
          },
          "mode": "count",
          "field": "req_lw_ip_address_ss",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 20,
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "logAxis": false,
          "arrangement": "horizontal",
          "chart": "pie",
          "counter_pos": "above",
          "lastColor": "",
          "spyable": true,
          "show_queries": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "User IP Address",
          "sortBy": "count",
          "exportSize": 10000
        }
      ]
    },
    {
      "title": "Table",
      "height": "150px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 12,
          "editable": true,
          "type": "table",
          "loadingEditor": false,
          "status": "Stable",
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&sort=timestamp_tdt desc&wt=json&rows=125",
            "basic_query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&sort=timestamp_tdt desc",
            "custom": ""
          },
          "size": 25,
          "pages": 5,
          "offset": 0,
          "sort": [
            "timestamp_tdt",
            "desc"
          ],
          "group": "default",
          "style": {
            "font-size": "9pt"
          },
          "overflow": "min-height",
          "fields": [
            "timestamp_tdt",
            "q_s",
            "numdocs_l",
            "qtime_l",
            "req_lw_user_ss",
            "req_lw_ip_address_ss",
            "req_lw_city_ss",
            "req_lw_state_ss",
            "clicked_count_l",
            "req_lw.pipelineId_ss"
          ],
          "important_fields": [
            "_version_",
            "clicked_count_l",
            "collection_s",
            "httpmethod_s",
            "id",
            "numdocs_l",
            "q_s",
            "q_txt",
            "qtime_l",
            "req_boost_ss",
            "req_defType_ss",
            "req_ds_EnterpriseSearch-Sharepoint_ss",
            "req_f.DeptName_s.facet.mincount_ss",
            "req_f.DeptName_s.facet.missing_ss",
            "req_f.DeptName_s.facet.sort_ss",
            "req_f.EmployeeTitle_s.facet.mincount_ss",
            "req_f.EmployeeTitle_s.facet.missing_ss",
            "req_f.EmployeeTitle_s.facet.sort_ss",
            "req_f.authorsX_ss.facet.limit_ss",
            "req_f.authorsX_ss.facet.mincount_ss",
            "req_f.authorsX_ss.facet.missing_ss",
            "req_f.authorsX_ss.facet.sort_ss",
            "req_f.data_sourceX_s.facet.limit_ss",
            "req_f.data_sourceX_s.facet.mincount_ss",
            "req_f.data_sourceX_s.facet.missing_ss",
            "req_f.data_sourceX_s.facet.sort_ss",
            "req_f.extracted_namesX_ss.facet.mincount_ss",
            "req_f.extracted_namesX_ss.facet.missing_ss",
            "req_f.file_formatX_s.facet.mincount_ss",
            "req_f.file_formatX_s.facet.missing_ss",
            "req_f.file_formatX_s.facet.sort_ss",
            "req_f.question_typeX_s.facet.mincount_ss",
            "req_f.question_typeX_s.facet.missing_ss",
            "req_f.topicX_s.facet.mincount_ss",
            "req_f.topicX_s.facet.missing_ss",
            "req_facet.field_ss",
            "req_facet.pivot.min.count_ss",
            "req_facet.pivot_ss",
            "req_facet_ss",
            "req_fl_ss",
            "req_fq_ss",
            "req_hl.fl_ss",
            "req_hl.fragsize_ss",
            "req_hl.preserveMulti_ss",
            "req_hl.q_ss",
            "req_hl_ss",
            "req_isFusionQuery_ss",
            "req_lw.pipelineId_ss",
            "req_lw_appName_ss",
            "req_lw_browser_ss",
            "req_lw_city_ss",
            "req_lw_coord_ss",
            "req_lw_country_ss",
            "req_lw_facet.pivot_ss",
            "req_lw_ip_address_ss",
            "req_lw_language_ss",
            "req_lw_q_orig_ss",
            "req_lw_signals_filter_ss",
            "req_lw_state_ss",
            "req_lw_userAgent_ss",
            "req_lw_user_device_ss",
            "req_lw_user_ss",
            "req_lw_uuid_ss",
            "req_lw_zip_code_ss",
            "req_pf_ss",
            "req_q_ss",
            "req_qf_ss",
            "req_rows_ss",
            "req_start_ss",
            "req_wrapped_ds_EnterpriseSearch-Sharepoint_ss",
            "req_wt_ss",
            "timestamp_tdt",
            "totaltime_l"
          ],
          "highlight": [],
          "sortable": true,
          "header": true,
          "paging": true,
          "field_list": false,
          "trimFactor": 300,
          "normTimes": true,
          "spyable": true,
          "saveOption": "json",
          "exportSize": 125,
          "exportAll": true,
          "displayLinkIcon": true,
          "imageFields": [],
          "imgFieldWidth": "auto",
          "imgFieldHeight": "85px",
          "show_queries": true,
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "Table",
          "maxNumCalcTopFields": 20,
          "calcTopFieldValuesFromAllData": false
        }
      ]
    },
    {
      "title": "Geo",
      "height": "240px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "span": 4,
          "editable": true,
          "type": "map",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&rows=0&facet=true&facet.field=req_lw_state_ss&facet.limit=100",
            "custom": ""
          },
          "mode": "count",
          "field": "req_lw_state_ss",
          "stats_field": "",
          "decimal_points": 0,
          "map": "usa",
          "useNames": false,
          "colors": [
            "#A0E2E2",
            "#265656"
          ],
          "size": 100,
          "exclude": [],
          "spyable": true,
          "index_limit": 0,
          "show_queries": true,
          "title": "Map"
        },
        {
          "span": 4,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&facet=true&facet.field=req_lw_country_ss&facet.limit=10&facet.missing=true&f.req_lw_country_ss.facet.sort=count",
            "custom": ""
          },
          "mode": "count",
          "field": "req_lw_country_ss",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 10,
          "sortBy": "count",
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "logAxis": false,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "exportSize": 10000,
          "lastColor": "",
          "spyable": true,
          "show_queries": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "Country"
        },
        {
          "span": 4,
          "editable": true,
          "type": "terms",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&facet=true&facet.field=req_lw_user_ss&facet.limit=10&facet.missing=true&f.req_lw_user_ss.facet.sort=count",
            "custom": ""
          },
          "mode": "count",
          "field": "req_lw_user_ss",
          "stats_field": "",
          "decimal_points": 0,
          "exclude": [],
          "missing": false,
          "other": false,
          "size": 10,
          "sortBy": "count",
          "order": "descending",
          "style": {
            "font-size": "10pt"
          },
          "donut": false,
          "tilt": false,
          "labels": true,
          "logAxis": false,
          "arrangement": "horizontal",
          "chart": "bar",
          "counter_pos": "above",
          "exportSize": 10000,
          "lastColor": "",
          "spyable": true,
          "show_queries": true,
          "chartColors": [
            "#7EB26D",
            "#EAB839",
            "#6ED0E0",
            "#EF843C",
            "#E24D42",
            "#1F78C1",
            "#BA43A9",
            "#705DA0",
            "#508642",
            "#CCA300",
            "#447EBC",
            "#C15C17",
            "#890F02",
            "#0A437C",
            "#6D1F62",
            "#584477",
            "#B7DBAB",
            "#F4D598",
            "#70DBED",
            "#F9BA8F",
            "#F29191",
            "#82B5D8",
            "#E5A8E2",
            "#AEA2E0",
            "#629E51",
            "#E5AC0E",
            "#64B0C8",
            "#E0752D",
            "#BF1B00",
            "#0A50A1",
            "#962D82",
            "#614D93",
            "#9AC48A",
            "#F2C96D",
            "#65C5DB",
            "#F9934E",
            "#EA6460",
            "#5195CE",
            "#D683CE",
            "#806EB7",
            "#3F6833",
            "#967302",
            "#2F575E",
            "#99440A",
            "#58140C",
            "#052B51",
            "#511749",
            "#3F2B5B",
            "#E0F9D7",
            "#FCEACA",
            "#CFFAFF",
            "#F9E2D2",
            "#FCE2DE",
            "#BADFF4",
            "#F9D9F9",
            "#DEDAF7"
          ],
          "refresh": {
            "enable": false,
            "interval": 2
          },
          "title": "Users"
        }
      ]
    },
    {
      "title": "Map",
      "height": "500px",
      "editable": true,
      "collapse": true,
      "collapsable": true,
      "panels": [
        {
          "span": 12,
          "editable": true,
          "type": "bettermap",
          "loadingEditor": false,
          "queries": {
            "mode": "all",
            "ids": [
              0
            ],
            "query": "q=*%3A*&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*&wt=json&rows=1000&fq=timestamp_tdt:[NOW/YEAR-1YEAR%20TO%20NOW/YEAR%2B1YEAR]&sort=timestamp_tdt desc",
            "custom": "&fq=req_lw_coord_ss:*"
          },
          "size": 1000,
          "spyable": true,
          "lat_start": "",
          "lat_end": "",
          "lon_start": "",
          "lon_end": "",
          "field": "req_lw_coord_ss",
          "show_queries": true,
          "title": "Map",
          "fitBoundsAuto": true,
          "lat_empty": 0,
          "lon_empty": 0
        }
      ]
    },
    {
      "title": "Applied Filters",
      "height": "240px",
      "editable": true,
      "collapse": false,
      "collapsable": true,
      "panels": [
        {
          "error": false,
          "span": 12,
          "editable": true,
          "spyable": true,
          "group": [
            "default"
          ],
          "type": "filtering",
          "title": "Filters"
        }
      ]
    }
  ],
  "editable": true,
  "index": {
    "interval": "none",
    "pattern": "[logstash-]YYYY.MM.DD",
    "default": "_all"
  },
  "style": "dark",
  "failover": false,
  "panel_hints": true,
  "loader": {
    "save_gist": false,
    "save_elasticsearch": true,
    "save_local": true,
    "save_default": true,
    "save_temp": true,
    "save_temp_ttl_enable": true,
    "save_temp_ttl": "30d",
    "load_gist": true,
    "load_elasticsearch": true,
    "load_elasticsearch_size": 20,
    "load_local": true,
    "hide": false,
    "dropdown_collections": true,
    "save_as_public": false
  },
  "solr": {
    "server": "/api/apollo/solr/",
    "core_name": "EnterpriseSearch_logs",
    "core_list": [
      "BestBuy_rules",
      "UserPrefs_signals",
      "KM_signals_aggr",
      "default_signals",
      "EnterpriseSearch2_signals_aggr",
      "UserPrefs_signals_aggr",
      "system_metrics",
      "system_blobs",
      "EnterpriseSearch_signals",
      "POI_signals",
      "default_syn_c3lub255bXMudHh0",
      "logs",
      "EnterpriseSearch",
      "citibikerides_signals",
      "EnterpriseSearch_signals_aggr",
      "citibikerides_logs",
      "POI_signals_aggr",
      "KM_logs",
      "POI",
      "default_signals_aggr",
      "EnterpriseSearch2_signals",
      "Doctors",
      "BestBuy_signals_aggr",
      "EnterpriseSearch2_logs",
      "BestBuy_signals",
      "BestBuy_syn_c3lub255bXMudHh0",
      "UserPrefs_logs",
      "EnterpriseSearch_syn_c3lub255bXMudHh0",
      "EnterpriseSearch2",
      "system_messages",
      "recommender_models",
      "citibikerides_signals_aggr",
      "audit_logs",
      "Doctors_signals_aggr",
      "POI_logs",
      "KM_signals",
      "default",
      "default_logs",
      "BestBuy_logs",
      "system_jobs_history",
      "BestBuy",
      "citibikerides",
      "UserPrefs",
      "Doctors_signals",
      "KM",
      "EnterpriseSearch_stored_parameters",
      "Doctors_logs",
      "system_history",
      "BestBuy_stored_parameters",
      "EnterpriseSearch_logs"
    ],
    "global_params": "&df=q_txt&fq=-req_lw_ignoreInLogs_ss:true&fq=req_lw_appName_ss:*"
  },
  "username": "admin"
}